title: Xray Tomography
application domain: CoFI Examples -> 37 EARTH SCIENCES -> 3706 Geophysics -> 370609 Seismology and seismic exploration -> Xray Tracer -> Xray Tomography
description: We look at a linear inverse problem based on Xray Tomography
method:
  xray_tomography.ipynb:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
  xray_tomography_linear_solver.py:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
