title: Xray Tomography
application domain: CoFI Examples -> EARTH SCIENCES -> Geophysics -> Seismology And Seismic Exploration -> Travel times -> Straight-ray tomography
description: We look at a linear inverse problem based on Xray Tomography
method:
  xray_tomography.ipynb:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
  xray_tomography_linear_solver.py:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
