title: Linear Regression
application domain: CoFI Examples -> MATHEMATICAL SCIENCES -> Statistics -> Applied statistics -> Curve fitting -> Linear regression
description: Linear regression problem solved by linear solver, optimizer and sampler
method:
  linear_regression.ipynb:
  linear_regression_sealevel.ipynb:
  linear_regression_emcee_sampler.py:
  linear_regression_linear_system_solver.py:
  linear_regression_linear_system_general.py:
  linear_regression_optimizer_lstsq.py:
  linear_regression_optimizer_minimize.py:
  linear_regression_pytorch_optim.py:
