title: Linear Regression
application domain: CoFI Examples -> MATHEMATICAL SCIENCES -> Statistics -> Applied statistics -> Curve fitting -> Linear regression
description: Linear regression problem solved by linear solver, optimizer and sampler
method:
  linear_regression.ipynb:
    description: Demonstrates polynomial curve fitting with matrix based linear solver, scipy optimisation of a misfit, and Bayesian sampling of a posterior PDF.
    methods:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> BFGS
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
  linear_regression_sealevel.ipynb:
    description: Demonstrates polynomial curve fitting of a real Sea level dataset using a matrix based linear solver, scipy optimisation of a misfit, and Bayesian sampling of a posterior PDF, with user challenges.
    methods:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
  linear_regression_emcee_sampler.py:
    description: Script demonstrating Bayesian sampling with emcee in a simple polynomial regression problem.
    methods:
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
  linear_regression_linear_system_solver.py:
    description: Script demonstrating (local) matrix based solver for a simple polynomial regression problem.
    methods:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
  linear_regression_linear_system_general.py:
    description: Script demonstrating scipy Least Squares matrix based solver for a simple polynomial regression problem.
    methods:
    - CoFI -> Parameter estimation -> Matrix based solvers -> Linear system solvers -> scipy.linalg.lstsq -> gelsd
  linear_regression_optimizer_lstsq.py:
    description: Script demonstrating scipy misfit optimisation based solver for a simple polynomial regression problem.
    methods:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.least_squares -> trf
  linear_regression_optimizer_minimize.py:
    description: Script demonstrating scipy misfit optimisation based solver for a simple polynomial regression problem.
    methods:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> BFGS
  linear_regression_pytorch_optim.py:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> torch.optim -> Adam
