title: Receiver Function Inversion
application domain: 37 EARTH SCIENCES -> 3706	Geophysics -> 370609 Seismology and seismic exploration -> Receiver function -> ReceiverFunctionInversion
description: We run inversion on a toy receiver function model with optimization and sampling in this example
method:
  receiver_function_inversion.ipynb:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Nelder-Mead
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
