name: cofi_env
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - python>=3.8
  - jupyterlab>=3
  - scipy=1.12
  - matplotlib>=3.5.0
  - nodejs>=12
  - pygimli>=1.5.0
  - shapely
  - cython
  - cartopy
  - pip
  - pip:
    - cofi>=0.2.8
    - geo-espresso>=0.3.13
    - ipywidgets>=7.7.0
    - tqdm>=4.0
    - seislib>=0.6.7
    - git+https://github.com/inlab-geo/pysurf96.git@ctypes
