title: FMM Tomography
application domain: 37 EARTH SCIENCES -> 3706	Geophysics -> 370609 Seismology and seismic exploration -> Fast Marching Method -> FMM tomography
description: Seismic wave tomography via fast marching method
method:
  fmm_tomography.ipynb:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> cofi.simple_newton -> Newton's method in optimization
  fmm_tomography_regularization_discussion.ipynb:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> cofi.simple_newton -> Newton's method in optimization
  fmm_tomography_gaussian_prior_scipy_opt.py:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Newton-CG
  fmm_tomography_simple_newton.py: 
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> cofi.simple_newton -> Newton's method in optimization
