title: PyGIMLi DCIP
application domain: CoFI Examples -> 37 EARTH SCIENCES -> 3706 Geophysics -> 370602 Electrical and electromagnetic methods in geophysics -> Direct current and induced polarization -> DCIP
description: Using the DCIP solver provided by PyGIMLi, we use different CoFI solvers to solve the corresponding inverse problem
method:
  pygimli_dcip.ipynb: 
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> torch.optim -> RAdam
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> trust-ncg
  pygimli_dcip_century_tri_mesh.ipynb: 
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> trust-ncg
