title: VTEM max Thin plate inversion
application domain: CoFI Examples -> EARTH SCIENCES -> Geophysics -> Electrical and electromagnetic methods in geophysics -> Electromagnetic -> Thin plate approximation
description: Using the forward solver provided by P223 and CoFI to invert for a thin plate target
method:
  thin_pate_inversion.ipynb: 
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Newton-CG
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
  single_survey_line.ipynb:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Newton-CG
  single_survey_line_vertical_only.ipynb:
      - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Newton-CG
  three_survey_lines_parameter_estimation.ipynb:
    - CoFI -> Parameter estimation -> Optimization -> Non linear -> scipy.optimize.minimize -> Newton-CG
  three_survey_lines_smt_baysbay.ipynb:
    - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> bayesbay -> VanillaSampler
  three_survey_lines_smt_emcee.ipynb:
   - CoFI -> Ensemble methods -> Bayesian sampling -> McMC samplers -> emcee -> StretchMove
  three_survey_lines_smt_neighpy.ipynb:
    - CoFI -> Ensemble methods -> Direct search  -> Monte Carlo -> Neighpy

